### ISSUE TITLE
Connectors references

### ISSUE THREAD

**Issue by EdShine13** [FCare/SataTo3DO#1]
I can't find the references of the two connectors (power1/cd-rom).

**Comment by tzmwx** [comment]
The 1.5mm mark is incorrect and should be a 1.25 mm fpc socket

**Comment by EdShine13** [comment]
Thanks for your answer but I find 1.0mm not 1.25mm

**Comment by tzmwx** [comment]
google“1.25MM FFC POST PLATED V 30P”
