### ISSUE TITLE
System not booting into menu

### ISSUE THREAD

**Issue by sudo-lupus666** [FCare/SataTo3DO#3]
Hi, everyone. First of all, thank you for sharing this project with the community!

I've got my board assembled like this:

https://imgur.com/a/o36HQKc

I'm using the uf2 pre-compiled file from the release. My thumbstick is in a fat32 format. Inside it, there's the boot.iso and one game, inside a folder.

When I turn the console on, It goes to the 3DO logo and after that, I've got a black screen. After some seconds, the console reboots and the access led indicator starts blinking, but the screen continues black. 

Any ideas??

**Comment by sudo-lupus666** [comment]
Got it working recompiling the source. Ty again!

**Comment by hpx1984** [comment]
hi Iupus666

could you share the recompiling file ?
